// <auto-generated />
namespace News.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class expandemailfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(expandemailfield));
        
        string IMigrationMetadata.Id
        {
            get { return "202111231629206_expand-email-field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
